// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("Grass.SqlDb")>]
[<assembly: AssemblyProductAttribute("ZZZ")>]
[<assembly: AssemblyDescriptionAttribute("ZZZ")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyCompanyAttribute("ZZZ")>]
[<assembly: AssemblyCopyrightAttribute("Copyright © ZZZ")>]
[<assembly: ComVisibleAttribute(false)>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Grass.SqlDb"
    let [<Literal>] AssemblyProduct = "ZZZ"
    let [<Literal>] AssemblyDescription = "ZZZ"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyCompany = "ZZZ"
    let [<Literal>] AssemblyCopyright = "Copyright © ZZZ"
    let [<Literal>] ComVisible = false
