// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("Savanna.Core")>]
[<assembly: AssemblyProductAttribute("XLCatlin.DataLab.XCBRA")>]
[<assembly: AssemblyDescriptionAttribute("Component of XLCatlin.DataLab.XCBRA")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyCompanyAttribute("XL Catlin")>]
[<assembly: AssemblyCopyrightAttribute("Copyright © XL Catlin 2017")>]
[<assembly: ComVisibleAttribute(false)>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Savanna.Core"
    let [<Literal>] AssemblyProduct = "XLCatlin.DataLab.XCBRA"
    let [<Literal>] AssemblyDescription = "Component of XLCatlin.DataLab.XCBRA"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyCompany = "XL Catlin"
    let [<Literal>] AssemblyCopyright = "Copyright © XL Catlin 2017"
    let [<Literal>] ComVisible = false
